# File: .github/workflows/repo-sync.yml

on:
  push:
    branches:
      - master

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: repo-sync
        uses: wei/git-sync@v2
        with:
          source_repo: "https://github.com/yoavain/yoavain.git"
          source_branch: "master"
          destination_repo: "https://github.com/yoavain-sundaysky/yoavain-sundaysky.git"
          destination_branch: "master"
